apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-example.fullname" . }}
  labels:
    app.kubernetes.io/component: producer
    {{- include "kafka-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: producer
    {{- include "kafka-example.selectorLabels" . | nindent 4 }}
