serviceMonitor:
  enabled: true
  additionalLabels:
    prometheus: kube-prometheus

read:
  replicas: 1
  
write:
  replicas: 1

backend:
  replicas: 1

minio:
  enabled: true
  
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
