agentCollector:
  enabled: false
# deploy additional standalone collector
standaloneCollector:
  enabled: true
  configOverride:
    receivers:
      otlp:
        protocols:
          http:
            # allow other origin for testing
            cors_allowed_origins:
              - http://localhost:3000
              - http://localhost:80


ingress:
  enabled: true
  hosts:
    - host: collector.testing.com
      paths:
        - path: /
          pathType: Prefix
          port: 4318
