commonLabels:
  prometheus: kube-prometheus

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.testing.com

  additionalDataSources:
   - name: Loki
     access: proxy
     editable: false
     orgId: 1
     type: loki
     url: http://loki:3100
     version: 1
   - name: Tempo
     access: proxy
     editable: false
     orgId: 1
     type: tempo
     url: http://tempo:3100
     version: 1

  serviceMonitor:
    enabled: true
    additionalLabels:
      prometheus: kube-prometheus

prometheus:
  prometheusSpec:
    # define label to monitor external service monitor objects
    serviceMonitorSelector:
      matchLabels:
        prometheus: kube-prometheus
