grafana:
  ingress:
    enabled: true

  additionalDataSources:
   - name: Loki
     access: proxy
     editable: false
     orgId: 1
     type: loki
     url: http://loki:3100
     version: 1
   - name: Tempo
     access: proxy
     editable: false
     orgId: 1
     type: tempo
     url: http://tempo
     version: 1
