kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.23.4@sha256:0e34f0d0fd448aa2f2819cfd74e99fe5793a6e4938b328f657c8e3f81ee0dfb9
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # KAFKA
      - containerPort: 9094
        hostPort: 9094
        protocol: TCP
      # OTLP GRCP
      - containerPort: 4317
        hostPort: 4317
        protocol: TCP
      # OTLP HTTP
      - containerPort: 4318
        hostPort: 4318
        protocol: TCP
