---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: strimzi
spec:
  kafka:
    replicas: 1
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: false
      - name: external1
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: persistent-claim
      size: 10Gi
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: strimzi
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
