namespaces:
  ingress:
  strimzi:
  monitoring:
  app:

helmRepos:
  ot-helm: "https://ot-container-kit.github.io/helm-charts/"
  strimzi: "https://strimzi.io/charts/"
  open-telemetry: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  grafana: "https://grafana.github.io/helm-charts"
  prometheus-community: https://prometheus-community.github.io/helm-charts
  ingress-nginx: https://kubernetes.github.io/ingress-nginx
  jaegertracing: https://jaegertracing.github.io/helm-charts

apps:
  kube-prometheus:
    enabled: true
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 19.3.0
    valuesFiles:
      -  ./kube-prometheus/values.yaml
    priority: -100
  otlp-agent:
    enabled: true
    namespace: monitoring
    chart: ./opentelemetry/charts/opentelemetry-collector
    version: 0.8.0
    valuesFiles:
      - ./opentelemetry/common.yaml
      - ./opentelemetry/agent/values.yaml
    priority: -95
  otlp-collector:
    enabled: true
    namespace: monitoring
    chart: ./opentelemetry/charts/opentelemetry-collector
    version: 0.8.0
    valuesFiles:
      - ./opentelemetry/common.yaml
      - ./opentelemetry/collector/values.yaml
    priority: -95
  ingress-nginx:
    enabled: true
    wait: true # wait till ready, else it will to call the ingress admission webhooks
    namespace: ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.0.13
    valuesFiles:
      - ./ingress-nginx/values.yaml
    priority: -90
  loki:
    enabled: true
    namespace: monitoring
    chart: grafana/loki
    version: 2.8.1
    valuesFiles:
      - ./loki/values.yaml
    priority: -85
  tempo:
    enabled: true
    namespace: monitoring
    chart: grafana/tempo
    version: 0.9.0
    valuesFiles:
      - ./tempo/values.yaml
    priority: -80
  strimzi-operator:
    enabled: true
    namespace: strimzi
    chart: strimzi/strimzi-kafka-operator
    version: 0.26.0
    valuesFiles:
      - ./strimzi/values.yaml

# example applictions
  snapshot:
    enabled: true
    namespace: app
    chart: ../apps/snapshot/helm
    version: 0.1.0
    valuesFiles:
      - ./snapshot/values.yaml
  report:
    enabled: true
    namespace: app
    chart: ../apps/report/helm
    version: 0.1.0
    valuesFiles:
      - ./report/values.yaml
