namespaces:
  ingress:
  strimzi:
  monitoring:

helmRepos:
  ot-helm: "https://ot-container-kit.github.io/helm-charts/"
  strimzi: "https://strimzi.io/charts/"
  open-telemetry: "https://open-telemetry.github.io/opentelemetry-helm-charts"
  grafana: "https://grafana.github.io/helm-charts"
  prometheus-community: https://prometheus-community.github.io/helm-charts
  ingress-nginx: https://kubernetes.github.io/ingress-nginx
  jaegertracing: https://jaegertracing.github.io/helm-charts

apps:
  kube-prometheus:
    enabled: true
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 19.2.2
    valuesFiles:
      -  ./kube-prometheus/values.yaml
    priority: -95
  ingress-nginx:
    enabled: true
    namespace: ingress
    chart: ingress-nginx/ingress-nginx
    version: 4.0.6
    valuesFiles:
      - ./ingress-nginx/values.yaml
    priority: -90
  loki:
    enabled: true
    namespace: monitoring
    chart: grafana/loki
    version: 2.6.0
    valuesFiles:
      - ./loki/values.yaml
    priority: -85
  tempo:
    enabled: true
    namespace: monitoring
    chart: ../../grafana-helm-charts/charts/tempo
    version: 0.8.0
    valuesFiles:
      - ./tempo/values.yaml
    priority: -80
  otlp-agent:
    enabled: true
    namespace: monitoring
    chart: ../../opentelemetry-helm-charts/charts/opentelemetry-collector
    version: 0.7.0
    valuesFiles:
      - ./opentelemetry/common.yaml
      - ./opentelemetry/agent/values.yaml
    priority: -75
  otlp-collector:
    enabled: true
    namespace: monitoring
    chart: ../../opentelemetry-helm-charts/charts/opentelemetry-collector
    version: 0.7.0
    valuesFiles:
      - ./opentelemetry/common.yaml
      - ./opentelemetry/collector/values.yaml
    priority: -75
  strimzi-operator:
    enabled: true
    namespace: strimzi
    chart: strimzi/strimzi-kafka-operator
    version: 0.25.0
