config:
  receivers:
    # TODO K8 Eventreceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver
    jaeger:
      protocols:
        thrift_compact:
          endpoint: 0.0.0.0:6831

  exporters:
    otlp:
      endpoint: tempo:4317
      tls:
        insecure: true

    jaeger:
      endpoint: jaeger-collector:14250
      tls:
        insecure: true

    loki:
      endpoint: http://loki:3100/loki/api/v1/push
      #  tenant_id: "example"
      labels:
        attributes:
          # Allowing 'k8.container.name' attribute and transform it to 'container_name', which is a valid Loki label name.
          k8s.container.name: "container"
          k8s.namespace.name: "namespace"
          k8s.pod.name: "pod"
          k8s.cluster.name: "k8s_cluster_name"
          # Allowing 'severity' attribute and not providing a mapping, since the attribute name is a valid Loki label name.
          severity: ""
          http.status_code: "http_status_code"
      headers:
        "X-Custom-Header": "loki_rocks"

  service:
    #    telemetry:
    #      logs:
    #        level: "debug"
    pipelines:
      logs:
        exporters:
          - loki
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      traces:
        exporters:
          - otlp
          - jaeger
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - jaeger
          - zipkin
