config:
    # TODO K8 Eventreceiver https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver

  exporters:
    otlp:
      endpoint: tempo:4317
      tls:
        insecure: true

    otlp/jaeger:
      endpoint: jaeger-collector:4317
      tls:
        insecure: true

    loki:
      endpoint: http://loki-gateway/loki/api/v1/push

  service:
    pipelines:
      logs:
        exporters:
          - loki
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      traces:
        exporters:
          - otlp
          - otlp/jaeger
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      metrics: null
