
controller:
  # forward traces to otlp collector running on the same node
  config:
    enable-opentelemetry: true
    otlp-collector-host: "otlp-collector-opentelemetry-collector.monitoring.svc.cluster.local"
  
  opentelemetry:
    enabled: true

  watchIngressWithoutClass: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        prometheus: kube-prometheus


  # these are Kind specific, this allows to forward port 80 and 443 on the host so that the ingress is reachable using localhost
  updateStrategy:
    type: Recreate
  hostPort:
    enabled: true
  service:
    type: NodePort

defaultBackend:
  enabled: true
