agent:
  enabled: true
  
collector:
  enabled: true
  service:
    otlp:
      grpc:
        name: otlp-grpc
        port: 4317
      http:
        name: otlp-http
        port: 4318
  
query:
  enabled: true
